### ISSUE TITLE
Angular, Homework 1, Tasks 1-2

### ISSUE THREAD

**Issue by DinamickaDevelopment** [StepanNaryshkov/StepanAngular#1]
Используйте английски язык для комментариев кода и других задач или исправьте кодировку, русские буквы не отображаются.

**Comment by StepanNaryshkov** [comment]
Добавил кодировку на страницу

**Comment by DinamickaDevelopment** [comment]
Ошибка в тегах, не корректно указаны.

**Comment by DinamickaDevelopment** [comment]
Нет проверки на пустые поля в форме (Task2)

**Comment by StepanNaryshkov** [comment]
Поправил
